id = "some-metal"
name = "Some-Metal"
version = "0.1.8"
schema_version = 1
authors = ["msdfsf"]
description = "Themes inspired by some metal covers."
repository = "https://github.com/msdfsf/some-metal-zed"
